// Shared properties data — Properties.jsx aur ViewProperty.jsx dono yahan se import karenge

export const PROPERTIES_DATA = [
  {
    id: 1,
    title: 'Luxury Apartment – Marina Gate',
    location: 'Dubai Marina',
    type: 'Apartment',
    price: 'AED 2,400,000',
    beds: 3, baths: 2, area: '1,850 sqft',
    status: 'available',
    agent: 'Ahmed Al Rashid',
    description: 'Stunning luxury apartment with panoramic sea views in the heart of Dubai Marina. Features premium finishes, floor-to-ceiling windows, and access to world-class amenities.',
    images: [],
    features: ['Sea View', 'Gym', 'Pool', 'Parking', 'Balcony', '24/7 Security'],
    listed: '2025-01-15',
  },
  {
    id: 2,
    title: 'Premium Villa – Palm Jumeirah',
    location: 'Palm Jumeirah',
    type: 'Villa',
    price: 'AED 18,000,000',
    beds: 6, baths: 7, area: '8,200 sqft',
    status: 'sold',
    agent: 'Sara Johnson',
    description: 'Iconic beachfront villa on the Palm with private pool, lush garden and direct beach access. A truly exclusive lifestyle property.',
    images: [],
    features: ['Private Beach', 'Private Pool', 'Garden', 'Maid Room', 'Driver Room', 'Smart Home'],
    listed: '2024-10-05',
  },
  {
    id: 3,
    title: 'Studio – Downtown Views',
    location: 'Downtown Dubai',
    type: 'Apartment',
    price: 'AED 950,000',
    beds: 0, baths: 1, area: '520 sqft',
    status: 'available',
    agent: 'Mohamed Ali',
    description: 'Cozy studio with Burj Khalifa views in the vibrant Downtown district. Perfect for investors or young professionals.',
    images: [],
    features: ['Burj View', 'Gym', 'Pool', 'Concierge'],
    listed: '2025-02-01',
  },
  {
    id: 4,
    title: 'Office Space – DIFC Tower',
    location: 'DIFC',
    type: 'Office',
    price: 'AED 4,200,000',
    beds: 0, baths: 2, area: '2,100 sqft',
    status: 'rented',
    agent: 'Emily Roberts',
    description: 'Grade A office space in the prestigious DIFC financial district. Fitted with modern interiors and meeting rooms.',
    images: [],
    features: ['Fitted', 'Meeting Rooms', 'Parking', 'Reception', 'High Speed Internet'],
    listed: '2024-12-20',
  },
  {
    id: 5,
    title: '2BR Townhouse – JVC',
    location: 'JVC',
    type: 'Townhouse',
    price: 'AED 1,750,000',
    beds: 2, baths: 3, area: '2,400 sqft',
    status: 'available',
    agent: 'Khalid Hassan',
    description: 'Spacious 2-bedroom townhouse in Jumeirah Village Circle with private garden and rooftop terrace.',
    images: [],
    features: ['Private Garden', 'Rooftop Terrace', 'Maid Room', 'Parking'],
    listed: '2025-01-28',
  },
  {
    id: 6,
    title: 'Retail Shop – Deira Gold',
    location: 'Deira',
    type: 'Shop',
    price: 'AED 3,100,000',
    beds: 0, baths: 1, area: '980 sqft',
    status: 'reserved',
    agent: 'Priya Nair',
    description: 'Prime retail space in the famous Deira Gold Souk area, high footfall location ideal for jewellery and luxury goods.',
    images: [],
    features: ['Corner Unit', 'High Footfall', 'Display Windows', 'Storage Room'],
    listed: '2025-02-10',
  },
];
